### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zanebliss** [zanebliss/teva#1]
## Road to v1
- [ ] Make process long running with events
- [ ] Add ability to run in debug mode
- [ ] Add ability to prevent writing to reflog
  - This could be preventing writes, or removing entries
- [ ] Add multithreading (or multiprocess)
- [ ] Support runners
  - Syntax, linting, etc
- [ ] Support merge commits 
- [ ] Support deleted files

## Road to beta
- [x] Use worktrees
- [x] Change worktree directory 55e06c4
- [ ] Add ability to write to log file
- [ ] Add installation mechanism
- [x] #4
- [x] #5
- [ ] Handle `SIGTERM` and `SIGINT`
- [x] Support changed file list caching
- [ ] Improve error handling

## Misc
- [x] Extract git module
- [x] Extract rspec module
- [x] Improve command line arguments 85ee52e
- [ ] Harden from SHA implementation
- [ ] Add tests
- [ ] Hand roll colors
