### ISSUE TITLE
TODO: `0.1.0` release

### ISSUE THREAD

**Issue by zanebliss** [zanebliss/teva#11]
- [x] Provide arm and x86 release binaries
- [x] Add default rails test runner config instead of `rspec`
- [x] Support adding new runners
  - Syntax, linting, etc
- [x] Support deleted files
- [x] Use worktrees
- [x] Change worktree directory 55e06c4
- [x] Add installation mechanism
- [x] Handle `SIGTERM` and `SIGINT`
- [x] Support changed file list caching
- [x] Improve error handling
- [x] Extract git module
- [x] Extract rspec module
- [x] Improve command line arguments 85ee52e
- [x] Harden from SHA implementation
- [x] Add tests
- [x] Hand roll colors

## Repo maintenance
- [x] Add security measures
- [x] Add CI
- [x] Add permissions and merge changes

## README
- [x] Add acii art
- [x] Add installation steps
- [x] Add "why"
- [x] Add caveats
- [x] Add potential concerns
